#!/usr/bin/env bash
echo "Uploading to robot (racecar-66)..."
echo ""
rsync --cvs-exclude .git -avP /home/racecar/racecar_team2_ws/src/racecar/ racecar-66:team2-ws/src/racecar/
echo ""
echo "Upload complete."
echo "Note: This did not upload the .git dir. Git will be confused"
echo "Note: This did not delete any files. Old files may exist on the racecar.\n"
