---
# ---------------- #
# General parameters
  # visualization levels:
  #   0 - no viz, no impact on runtime
  #   1 - runtime viz, small but acceptable impact on runtime
  #   2 - extra viz, may slow down runtime
  #   3 - debug viz, may significantly slow down runtime
# ---------------- #

epsilon: 0.001

viz:
  topics:
    goals:
      next_goal: 
        level: 1
        # given in published messages/second
        rate_limit: 5
        type: "pose"
        color: [0,1,1,1]
      corridors:
        level: 1
        rate_limit: 5
        type: "segment"
        color: [0,1,0,1]
      walls:
        level: 2
        rate_limit: 5
        type: "segment"
        color: [1,0,1,1]
    obstacles:
      inadmissible:
        level: 3
        rate_limit: 3
        type: "omap"
        color: [0,0,0,1]
    path_search:
      best_path:
        level: 1
        rate_limit: 5
        type: "path"
        color: [0,0,0,1]
      viable_paths:
        level: 2
        rate_limit: 5
        type: "path"
        color: [0,0,0,1]
      complete_paths:
        level: 2
        rate_limit: 5
        type: "path"
        color: [0,0,0,1]
      speed:
        level: 1
        rate_limit: 10
        type: "float"
      steering:
        level: 1
        rate_limit: 10
        type: "float"

# wheel_base: 0.27
planning_freq: 4
execution_freq: 15

runtime_specific:
  racecar:
    scan_topic: "/scan"
    visualize_level: 1
  not_racecar:
    scan_topic: "/scan_throttle"
    visualize_level: 2

# --------------------------- #
# obstacle avoidance parameters
# --------------------------- #

# obstacle map size and discretization (bins/meter)
obstacle_map:
  discretization: 5
  xmin: -3
  xmax: 10
  ymin: -8
  ymax: 8
  # minimum distance to nearest obstacle to be considered admissible
  min_distance: 0.3
  # number of cells worth of spacing between admissibility check waypoints
  # higher is faster, but might result in jumping over obstacles
  admissible_hop: 2.0

# ----------------------- #
# Dynamics Model Parameters
# ----------------------- #

# dynamics:
#   # max acceleration in meters/sec or rad/sec
#   # for now these are guesses, testing should be used to find the optimal values
#   max_linear_accel: 5
#   max_linear_decel: -8
#   max_angular_accel: 1.5
  
#   # bounds on mechanical capabilities
#   # 10mph ~= 4.47 m/s
#   max_speed: 3
#   max_deflection: 0.35

# ----------------------- #
# Navigator Parameters
# (wall/corridor detection)
# ----------------------- #
navigator:
  # When we're in a corridor w/ no turns, how far out to set the goal
  straight_ahead_distance: 10

  # Anything shorter is not a wall
  min_wall_length: 0.5

  # Anything shorter is not a corridor
  min_corridor_width: 2.0

  # This amount of error is acceptable to merge into 1 wall
  same_wall_error_m: 2
  same_wall_error_b: 0.17 # roughly 10 degrees

# --------------------- #
# Path Planner Parameters
# --------------------- #

planner:
  # number of angle settings to consider at each speed
  # the real number of candidate paths will be twice this
  # number because it will consider both min/max speed settings
  # this number should be odd
  # the higher it is, the better the found path will be, but the longer it will take
  angular_branch_factor: 5

  # if the path is within this distance, the goal is considered met (meters)
  goal_distance_threshold: 0.25

  # if there is now path, and the car is stopped, it will
  # start to back up in a straight line at this speed
  backup_speed: -1.0

  # number of control states per branch
  control_decisions_per_segment: 6

  # max planning distance. paths are terminated when they are above this (meters)
  max_planning_dist: 5

  # heuristic bias
  # heuristic is biased (multiplied) by this value once computed
  # setting this high makes the search more like dfs, low is
  # more like bfs. 1 is theortically optimal?
  heuristic_bias: 1.07

# ------------------ #
# Emergency Parameters
# ------------------ #

emergency:
  # when the robot has an old path it can execute but is considered stuck, it applies
  # breaks as fast as possible while following the old path. This damp factor is applied to
  # steering to potentially smooth the path as the car stops. Set to 1 to follow original path
  stop_path_steering_damp_factor: 1.0

...
