# this file contains coefficients for the found curves at the given locations
---
dynamics:
  # use this data to determine which model to use, and interpolate between the given
  # polynomial coefficients where x=speed for the high slip regions
  steering_prediction:
    # gives predictions of path arc radius based off steering_angle and speed
    - steering_angle: 0.13
      models:
        - speed_range: [0,1.5]
          coefficients: 1.9
        - speed_range: [1.5,5]:
          coefficients: [0.224, -0.645, 2.368]
    - steering_angle: 0.15
      models:
        - speed_range: [0,1.7]
          coefficients: 1.6
        - speed_range: [1.7,5]:
          coefficients: []
    - steering_angle: 0.2
      models:
        - speed_range: [0,2]
          coefficients: 1.38
        - speed_range: [2,5]:
          coefficients: [0.331,-1.31,2.699]
    - steering_angle: 0.25
      models:
        - speed_range: [0,2]
          coefficients: 1.15
        - speed_range: [2,5]:
          coefficients: [0.242,-0.868,1.932]
    - steering_angle: 0.3
      models:
        - speed_range: [0,2]
          coefficients: 0.935
        - speed_range: [2,5]:
          coefficients: [0.476,-1.795,2.663]
    - steering_angle: 0.35
      models:
        - speed_range: [0,1.8]
          coefficients: 0.82
        - speed_range: [1.8,5]:
          coefficients: [0.312,-0.953,1.574]
    - steering_angle: 0.4
      models:
        - speed_range: [0,1.8]
          coefficients: 0.82
        - speed_range: [1.8 ,5]:
          coefficients: [0.312,-0.953,1.574]
  capabilities:
    - max_turn: 0.32
    # use this with ackermann steering for low slip speeds
    - optimized_wheelbase: 0.247
    # gives predictions of 